# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "pdf-generator"
  tags:
    - "public"
spec:
  type: "service"
  lifecycle: "production"
  owner: "heimdall"
  system: "m22"
