ARG version
FROM gotenberg/gotenberg:${version}

USER root

# Install Norwegian language pack and set up locales
RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends libreoffice-l10n-nn && \
    sed -i '/nn_NO.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set environment variables for Norwegian Bokmål
ENV LANG=nn_NO.UTF-8
ENV LANGUAGE=nn_NO:nn
ENV LC_ALL=nn_NO.UTF-8

COPY /fonts/* /usr/local/share/fonts/

USER gotenberg