name: "Build and deploy"

on:
    push:
        branches:
            - main

env:
    CI: true
    TZ: Europe/Oslo

jobs:
    version:
        name: Calculate Version
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version-string.outputs.version }}
            image: ${{ steps.version-string.outputs.image }}

        steps:
            - name: Generate version string
              id: version-string
              shell: bash
              run: |
                  version="$(date -u '+%Y.%m.%d-%H.%M')-$(echo "${GITHUB_SHA}" | cut -c1-7)"
                  echo "version=${version}" >> "$GITHUB_OUTPUT"
                  echo "image=ghcr.io/kartverket/pdf-generator:${version}" >> "$GITHUB_OUTPUT"

    package-image:
        name: Build and (conditionally) Push Docker Image
        runs-on: ubuntu-latest
        needs:
            - version
        permissions:
            contents: write
            packages: write

        steps:
            - uses: actions/checkout@v7

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Login to GitHub Container Registry
              if: github.ref == 'refs/heads/main'
              uses: docker/login-action@v4
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker image
              uses: docker/build-push-action@v7
              env:
                  image: ${{ needs.version.outputs.image }}
              with:
                  context: .
                  file: Dockerfile
                  build-args: |
                      version=8
                  push: ${{ github.ref == 'refs/heads/main' }}
                  tags: ${{ env.image }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Tag commit med artifaktversjon
              if: github.ref == 'refs/heads/main'
              run: |
                  git tag ${{ needs.version.outputs.version }}
                  git push origin ${{ needs.version.outputs.version }}

    pharos:
        name: Run Pharos
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs:
            - version
            - package-image
        permissions:
            actions: read
            packages: read
            contents: read
            security-events: write
        steps:
            - name: "Run Pharos"
              uses: kartverket/pharos@e5a5cf71dd41384d6d62c7d9b387851c0457e81b # v0.6.4
              with:
                  image_url: ${{ needs.version.outputs.image }}
                  trivy: true
                  tfsec: true
                  disable_severity_check: true

    deploy-dev:
        name: "Deploy Dev"
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs:
            - version
            - package-image
        permissions:
            actions: read
            contents: read
            id-token: write
        steps:
            - name: Deploy to Dev
              uses: kartverket/matrikkel-actions/heimdall-deploy@main
              with:
                  cluster: "atkv3-dev"
                  resource: ".skip/dev.yaml"
                  var: |
                      image=${{ needs.version.outputs.image }},version=${{ needs.version.outputs.version }}

    deploy-prodtest:
        name: "Deploy prodtest"
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs:
            - version
            - deploy-dev
        permissions:
            actions: read
            contents: read
            id-token: write
        steps:
            - name: Deploy to prodtest
              uses: kartverket/matrikkel-actions/heimdall-deploy@main
              with:
                  cluster: "atkv3-prod"
                  resource: ".skip/prodtest.yaml"
                  var: |
                      image=${{ needs.version.outputs.image }},version=${{ needs.version.outputs.version }}

    deploy-prod:
        name: "Deploy prod"
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs:
            - version
            - deploy-prodtest
        permissions:
            actions: read
            contents: read
            id-token: write
        steps:
            - name: Deploy to prod
              uses: kartverket/matrikkel-actions/heimdall-deploy@main
              with:
                  cluster: "atkv3-prod"
                  resource: ".skip/prod.yaml"
                  var: |
                      image=${{ needs.version.outputs.image }},version=${{ needs.version.outputs.version }}